//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 02:50:11 PM CDT 
//


package com.dell.asm.asmcore.asmmanager.client.servicetemplate;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IpRange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IpRange"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StartingIp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="EndingIp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IpRange", propOrder = {
    "id",
    "startingIp",
    "endingIp"
})
public class IpRange
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    @XmlElement(name = "Id")
    protected String id;
    @XmlElement(name = "StartingIp", required = true)
    protected String startingIp;
    @XmlElement(name = "EndingIp", required = true)
    protected String endingIp;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the startingIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartingIp() {
        return startingIp;
    }

    /**
     * Sets the value of the startingIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartingIp(String value) {
        this.startingIp = value;
    }

    /**
     * Gets the value of the endingIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndingIp() {
        return endingIp;
    }

    /**
     * Sets the value of the endingIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndingIp(String value) {
        this.endingIp = value;
    }

}
