//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.24 at 02:50:11 PM CDT 
//


package com.dell.asm.asmcore.asmmanager.client.servicetemplate;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StaticNetworkConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StaticNetworkConfiguration"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Gateway" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Subnet" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PrimaryDns" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SecondaryDns" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DnsSuffix" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IpRange" type="{http://pg.dell.com/asm/virtualservices/network}IpRange" maxOccurs="unbounded"/&gt;
 *         &lt;element name="IpAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StaticNetworkConfiguration", propOrder = {
    "gateway",
    "subnet",
    "primaryDns",
    "secondaryDns",
    "dnsSuffix",
    "ipRange",
    "ipAddress"
})
public class StaticNetworkConfiguration
    implements Serializable
{

    private final static long serialVersionUID = 100L;
    protected String gateway;
    protected String subnet;
    protected String primaryDns;
    protected String secondaryDns;
    protected String dnsSuffix;
    protected List<IpRange> ipRange;
    protected String ipAddress;

    /**
     * Gets the value of the gateway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGateway() {
        return gateway;
    }

    /**
     * Sets the value of the gateway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGateway(String value) {
        this.gateway = value;
    }

    /**
     * Gets the value of the subnet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubnet() {
        return subnet;
    }

    /**
     * Sets the value of the subnet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubnet(String value) {
        this.subnet = value;
    }

    /**
     * Gets the value of the primaryDns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryDns() {
        return primaryDns;
    }

    /**
     * Sets the value of the primaryDns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryDns(String value) {
        this.primaryDns = value;
    }

    /**
     * Gets the value of the secondaryDns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryDns() {
        return secondaryDns;
    }

    /**
     * Sets the value of the secondaryDns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryDns(String value) {
        this.secondaryDns = value;
    }

    /**
     * Gets the value of the dnsSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDnsSuffix() {
        return dnsSuffix;
    }

    /**
     * Sets the value of the dnsSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDnsSuffix(String value) {
        this.dnsSuffix = value;
    }

    /**
     * Gets the value of the ipRange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ipRange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIpRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IpRange }
     * 
     * 
     */
    public List<IpRange> getIpRange() {
        if (ipRange == null) {
            ipRange = new ArrayList<IpRange>();
        }
        return this.ipRange;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpAddress(String value) {
        this.ipAddress = value;
    }

    @Override
    public String toString() {
        return "StaticNetworkConfiguration{" +
                "gateway='" + gateway + '\'' +
                ", subnet='" + subnet + '\'' +
                ", primaryDns='" + primaryDns + '\'' +
                ", secondaryDns='" + secondaryDns + '\'' +
                ", dnsSuffix='" + dnsSuffix + '\'' +
                ", ipRange=" + ipRange +
                ", ipAddress='" + ipAddress + '\'' +
                '}';
    }
}
