"""
Author: Saikumar Kalyankrishnan/Mirlan Kaiyrbaev
Created: Feb 22nd 2017
Description: Object Repository for Dashboard Page
"""


class Dashboard():
    def DashboardObjects (self, key):
        DashboardObjects = {'title': "//*[@id='page_dashboard']//header//h1",
                            'page_dashboard': "page_dashboard",
                            'deployLearn': "deployLearn",
                            'templateLearn': 'templateLearn',
                            'viewServerPool': ".//a[contains(@title, 'View Server Pool')]",
                            'bottomDetails': "bottomDetails",
                            'storageGroup': ".//a[@href='#/devices/storage']",
                            'storage_group_used': ".//a[@href='#/devices/storage']/span[2]",
                            'resourcesHeader': ".//header/h1",
                            'servicesHeader': ".//h1[contains(.,'Services')]",
                            'grayTitle': "grayTitle",
                            'eachService': ".//*[@id='health']//a[@class='ng-binding']",
                            'serverUtilization': ".//h3[contains(.,'Server Utilization')]",
                            'totalStorageCapacity': ".//h3[contains(.,'Total Storage Capacity')]",
                            'activityLog': ".//h3[contains(.,'Activity Log')]",
                            'viewAll': "recentActivityViewAll",
                            'learn': ".//h3[contains(.,'Learn')]",
                            'totalServicesCount': "totalServicesCount",
                            'critical': ".//*[contains(@ng-if, 'servicecriticalcount')]",
                            'warning': ".//*[contains(@ng-if, 'servicewarningcount')]",
                            'inProgress': ".//*[contains(@ng-if, 'serviceunknowncount')]",
                            'pending': ".//*[contains(@ng-if, 'servicependingcount')]",
                            'healthy': ".//*[contains(@ng-if, 'servicesuccesscount')]",
                            # 'canceled': ".//a[@href='#/services/cancelled']",  devs removed from UI
                            'storage_used': ".//*[@id='dashboardStorageCapacityPie']/div/*[name()='svg']/*[name()='g'][1]/*[name()='g'][1]/*[name()='path'][1]",
                            'server_health_critical': ".//*[@id='serverHealthPie']/div/*[name()='svg']/*[name()='g'][1]/*[name()='g'][1]/*[name()='path' and contains(@class, 'highcharts-point highcharts-color-3')]",
                            'server_used': ".//*[@id='serverUtilizationPie']/div/*[name()='svg']/*[name()='g'][1]/*[name()='g'][1]/*[name()='path' and contains(@class, 'highcharts-point highcharts-color-0')]",
                            'server_used_tool': ".//*[@id='serverUtilizationPie']/div/div/span",
                            'storage_used_tooltip': ".//*[@id='dashboardStorageCapacityPie']/div/div/span",
                            'server_health_tooltip': ".//*[@id='serverHealthPie']/div/div/span",
                            'pageTitle': ".//*[@id='page_services']/header/div/h1",
                            'totalServices': ".//label[contains(.,'Total Services')]",
                            'totalServers': ".//a[contains(.,' Total Servers')]",
                            'recentActivityText': ".//div[@id='sidebar']/div[2]/ul[1]/li/div[1]/div",
                            'services': ".//div[@ng-repeat='service in home.services']",
                            'deployedBy': ".//strong[contains(.,'Deployed By:')]/following::span[1]",
                            'pools': ".//div[@id='poolbreakdown']/div[2]/div",
                            'serverTable': "serverTable",
                            'numberOfServers': ".//table[@id='serverTable']/tbody/tr",
                            'serversStatus': ".//table[@id='serverTable']/tbody/tr/td[4]",
                            'itemsFound': ".//span[@ng-if='itemCount == totalItems']",
                            'globalPool': ".//a[@title='View Server Pool: Global']",
                            'serverPools': ".//*[@id='serverPoolsGrid']/tbody/tr",
                            'deployLink': ".//*[@id='sidebar']//button[@id='deployLink']",
                            'chassis': ".//i[@class='ci-device-storage-blade-chassis-front']/..",
                            'servers': ".//i[@class='ci-device-tower-chassis']/..",
                            'switches': ".//i[@class='ci-device-storage-rack-switch-stack-horiz']/..",
                            'storage': ".//i[@class='ci-storage-volume-half-full-2']/..",
                            'createTemplateLink': ".//*[@id='createTemplateLink']",
                            'addExistingService': ".//button[@ng-click='home.addExistingService()']",
                            'serverCount': "serverCount",
                            'serverCritical': ".//a[@href='#/devices/server/red']",
                            'serverWarning': ".//a[@href='#/devices/server/yellow']",
                            'serverHealthy': ".//a[@href='#/devices/server/green']",
                            'serverUnknown': ".//a[@href='#/devices/server/unknown']",
                            'popUpDeploy': ".//h4[contains(.,'Deploy Service')]",
                            'popUpTemplate': ".//h4[contains(.,'Create Template')]",
                            'popUpAddService': ".//h4[contains(.,'Add Existing Service')]",
                            'btnClose': "btnClose",
                            'btnConfirm': "btnConfirm",
                            'headerPageServices': ".//section[@id='page_services']/header/div/h1",
                            'logsHeader': ".//h1[contains(.,'Logs')]",
                            'pagination': ".//*[@id='devicesGrid']/tfoot/tr/td/div/nav/ul/li[4]/span",
                            'nextPage': ".//i[@class='glyphicon glyphicon-forward']",
                            'resources_header': ".//*[@id='page_devices']/header/h1",
                            'resources': ".//*[@id='devicesGrid']/tbody/tr",
                            'freeGroupSpace': "equalfreegroupspace",
                            'lnkViewDeviceDetails': "lnkViewDeviceDetails",
                            'ddlView': "ddlView",
                            'showFilterLink': "showFilterLink",
                            'devicesFound': ".//*[@id='devicesGrid']/tfoot/tr/td/div/nav/ul/li/p/span",
                            }
        return DashboardObjects.get(key)
