"""
Author: Saikumar Kalyankrishnan
Created: Mar 14th 2017
Description: Object Repository for Resources Page
"""
from libs.product.objects.Common import Common

class ResourceObjectRepo(Common):
    def ResourcesObjects (self, key):
        ResourceObjects= {'title': "//*[@id='page_devices']//h1",
                        'menu_resources':".//*[@id='pinaccordion']/div[4]/div[1]/h4",
                        'resources_dropdown':".//*[@id='pinaccordion']/div[4]/div[1]/h4/a[2]/i[1]",
                        'all_resources':".//*[@id='pin-nav__005fresources']/div/ul/li[1]/button",
                        'server_pools':".//*[@id='pin-nav__005fresources']/div/ul/li[2]/button",
                        'all_resources_tab':"tabSummary",                        
                        'resource_table': "devicesGrid",                        
                        
                        'discover_device':".//*[@id='lnkDiscoverDevices']/parent::li[@class!='ng-hide']",
                        'run_inventory':".//*[@id='runInventoryLink']/parent::li[@class!='ng-hide']",
                        'remove_device':".//*[@id='removeDeviceLink']/parent::li[@class!='ng-hide']",
                        'update_resource':".//*[@id='updateFirmwareDeviceLink']/parent::li[@class!='ng-hide']",
                        'chassis_config':".//*[@id='configureDeviceLink']/parent::li[@class!='ng-hide']",
                        'export_all':".//*[@id='exportAllLink']/parent::li[@class!='ng-hide']",
                        'change_resource_state': ".//*[@id='changeResourceState']",
                        'export_all_option':"exportAllLink",
                        
                        'search_button':"showSearchLink",
                        'show_filter_button':"showFilterLink",
                        'hide_filter_button':"hideFilterLink",
                        'device_filter_dialog':"devices_filters",
                        'discovery_wizard':"page_discoveryWizard",
                        'resource_type_filter':"ddlView",
                        'health_filter':"ddlView2",
                        'service_filter':"ddlView3",
                        'resource_state_filter':"ddlView4",                        
                        'select_unmanaged_state':".//*[@id='updateManagedState-unmanaged']",
                        'select_managed_state':".//*[@id='updateManagedState-managed']",
                        'select_reserved_state':".//*[@id='updateManagedState-reserved']",
                        'options_expander':".//*[@id='devicePanel']//button[contains(@class,'dropdown-toggle')]",
                                             
                        'clear_all_filter':"clearFilterLink'] ",
                        'more_options':"devicePanel']/ul[1]/li[8]/div/button",
                        'select_all_devices':".//*[@id='selectAllDevices']",                        
                        'select_first_device':".//*[@id='devicesGrid']/tbody/tr[1]/td[1]/input",
                        'device_count':".//*[@id='devicesGrid']/tbody/tr",  
                        'select_device':".//*[@id='devicesGrid']/tbody/tr[6]/td[1]/input",
                        'view_details':".//*[@id='lnkViewDeviceDetails']",
                        'view_compliance_rpt':".//*[@id='firmwarestatus']/span/span/a",
                        'select_firmware_component':"firmware",
                        'launch_idrac':".//*[@id='launchiDRACGUILink']",
                        'view_details_header':".//*[@id='page_device_details']/div/header/h1/span[2]",
                        'summary_tab':".//*[@id='page_device_details']/div/div[2]/ul/li[1]/a",
                        'port_view':".//*[@id='page_device_details']/div/div[2]/ul/li[2]/a",
                        'NW_interfaces':".//*[@id='page_device_details']/div/div[2]/ul/li[3]/a",
                        'fw-sw-revisions':".//*[@id='page_device_details']/div/div[2]/ul/li[4]/a",
                        'cpu':".//*[@id='page_device_details']/div/div[2]/ul/li[5]/a",
                        'memory':".//*[@id='page_device_details']/div/div[2]/ul/li[6]/a",
                        'volumes':".//*[@id='page_device_details']/div/div[2]/ul/li[2]/a",
                        'blades':".//*[@id='page_device_details']/div/div[2]/ul/li[2]/a",
                        'ioms':".//*[@id='page_device_details']/div/div[2]/ul/li[3]/a",
                        'local_storage':".//*[@id='page_device_details']/div/div[2]/ul/li[7]/a",
                        'filter_storage':".//*[@id='device_controllers']/div/div/ul/li[2]/select",
                        'current_page':".//input[@ng-model='pageState.txtPage']",
                        'total_pages':".//input[@ng-model='pageState.txtPage']/parent::span",
                        'next_page':".//i[contains(@class,'glyphicon-forward')]",
                        'previous_page':".//i[contains(@class,'glyphicon-backward')]",
                        'first_page':".//i[contains(@class,'glyphicon-step-backward')]",
                        'last_page':".//i[contains(@class,'glyphicon-step-forward')]",
                        'resources_link':".//*[@class='breadcrumb']/li/a[contains(text(), 'Resources')]",
                        'enable_existing_ip':"rackAddressingModeExisting",
                        'enable_static_nw':"rackAddressingModeStatic",
                        'select_hw_network':"rackNetworkId",
                        'select_rack_credential':"rackCredentialId",
                        
                        'device_table_header':".//*[@id='devicesGrid']/thead/tr[1]/th",
                        'device_table_header_col':".//*[@id='devicesGrid']/thead/tr[1]/th[%(hid)d]",
                        'device_element':".//*[@id='devicesGrid']/tbody/tr[%(rid)d]/td[%(cid)d]",
                        'device_health':".//*[@id='devicesGrid']/tbody/tr[%(rid)d]/td[%(cid)d]/i",
                        'search_device_table':"//*[@id='devicesGrid']/tbody/tr/td[contains(.,'%(resId)s')]",
                        'select_device_by_info':"//*[@id='%(tid)s']/tbody/tr/td[contains(.,'%(resInfo)s')]/parent::tr/td/input[contains(@type,'checkbox')]",
                        'get_device_id_search_by_info':"//*[@id='devicesGrid']/tbody/tr/td[contains(.,'%(resInfo)s')]/parent::tr/td/a/span",
                        
                        'wizard_next':".//button[contains(text(), 'Next')]",
                        'wizard_finish':".//button[contains(text(), 'Finish')]",
                        'device_info_count':".//*[@id='deviceInfo']/div/div[3]/ul/li",
                        'device_info_name':".//*[@id='deviceInfo']/div/div[3]/ul/li[%(rid)d]/label",
                        'device_info_value':".//*[@id='deviceInfo']/div/div[3]/ul/li[%(rid)d]/span",
                        'performance_metrics':"memorySelectedTimeFrame",
                        'verify_vcenter_details':".//*[contains(@id,'vcenter__')]",
                        'expand_vcenter_details':"//h4[contains(text(),'vCenter Details')]/parent::div/div/span[1]",
                        'get_datacenters': "//ul[contains(@class,'list-unstyled vcenter')]/li/i[contains(@class,'datacenter')]/parent::li/span[contains(@data-bind,'text:')]",
                        'current_fw_version':"//*[@id='resourceFirmwareReportTable']/tbody/tr/td[contains(text(), '%(component)s')]/parent::tr/td[2]",
                        'expected_fw_version':"//*[@id='resourceFirmwareReportTable']/tbody/tr/td[contains(text(), '%(component)s')]/parent::tr/td[3]",
                        'launch_management_ip':"//*[@id='devicesGrid']/tbody/tr/td[contains(.,'%(resInfo)s')]/parent::tr/td[6]/a",
                        'idrac_fw_version':"//*[@id='infolist_table3']/tbody/tr/td[contains(text(), 'Firmware Version')]/parent::tr/td[2]",
                        'device_stats':".//h3[contains(., '%(refName)s')]",                        
                        'historical_graphs':"//*[contains(@config, '%(refName)s')]//*[contains(@class, 'highcharts-series ')]//*[@fill]",
                        'pie_charts':"//*[contains(@ng-if,'%(refName)s')]//*[contains(@class, 'highcharts-tracker')]/*[@fill]",
                        'chart_filter':".//div[contains(@ng-if, '%(refName)s')]/button",
                        'select_chart_filter':".//div[contains(@ng-if, '%(refName)s')]/ul/li/a[contains(.,'%(refOption)s')]",
                        'chart_xaxis':"//*[contains(@config,'%(refName)s')]//*[contains(@class, 'highcharts-xaxis ')]",
                        'firmware_table':"resourceFirmwareReportTable",
                        'health_tooltip':".//*[@id='devicesGrid']/tbody/tr/td[contains(., '%(refName)s')]/parent::tr/td[2]/a",
                        'get_datacenters':".//*[contains(@class,'vcenterdevice datacenter')]/parent::li",
                        'get_datacenter':".//*[contains(@class,'vcenterdevice datacenter')]/parent::li[%(refId)d]",
                        'get_clusters':".//*[contains(@class,'vcenterdevice datacenter')]/parent::li[contains(., '%(refDC)s')]//*[contains(@class,'vcenterdevice cluster')]/parent::li",
                        'get_cluster':".//*[contains(@class,'vcenterdevice datacenter')]/parent::li[contains(., '%(refDC)s')]//*[contains(@class,'vcenterdevice cluster')]/parent::li[%(refId)d]",
                        'get_hosts':".//*[contains(@class,'vcenterdevice cluster')]/parent::li[contains(., '%(refCluster)s')]//*[contains(@class,'vcenterdevice host')]/parent::li",
                        'get_host':".//*[contains(@class,'vcenterdevice cluster')]/parent::li[contains(., '%(refCluster)s')]//*[contains(@class,'vcenterdevice host')]/parent::li[%(refId)d]",
                        'get_vms':".//*[contains(@class,'vcenterdevice host')]/parent::li[contains(., '%(refHost)s')]//*[contains(@class,'vcenterdevice vm')]/parent::li",
                        'get_vm':".//*[contains(@class,'vcenterdevice host')]/parent::li[contains(., '%(refHost)s')]//*[contains(@class,'vcenterdevice vm')]/parent::li[%(refId)d]",
        
                        'server_pools_tab':"tabserverpools",
                        'server_pool_table': "serverPoolsGrid",
                        'server_table': "serverTable",
                        'users_table': "users_table",
                        'server_pool_filter':"ddlView5",
                        'blades_table':"bladesTable",
                        'ioms_table':"iomoduleTable",
                        'cpl_table':"tab_compellentStorage",
                        'eql_table':"device_equallogicvolumes",
                        
                        'device_details_row_count':".//*[@id='%(tid)s']/table/tbody/tr",
                        'device_details_table_header':".//*[@id='%(tid)s']/table/thead/tr[1]/th",
                        'device_details_table_header_col':".//*[@id='%(tid)s']/table/thead/tr[1]/th[%(hid)d]",
                        'device_details_table_element':".//*[@id='%(tid)s']/table/tbody/tr[%(rid)d]/td[%(cid)d]",
                        
                        'generic_row_count':".//*[@id='%(tid)s']/tbody/tr",
                        'generic_table_header':".//*[@id='%(tid)s']/thead/tr[1]/th",
                        'generic_table_header_col':".//*[@id='%(tid)s']/thead/tr[1]/th[%(hid)d]",
                        'generic_table_element':".//*[@id='%(tid)s']/tbody/tr[%(rid)d]/td[%(cid)d]",
                        'generic_table_header_cols':".//*[@id='%(tid)s']/tbody/tr[1]/td",
                        
                        'select_server_pool_by_row':".//*[@id='serverPoolsGrid']/tbody/tr[%(rid)d]",
                        'select_first_pool':".//*[@id='serverPoolsGrid']/tbody/tr[1]/td[1]/input",
                        'server_pool_servers_tab':"Servers",
                        'server_pool_users_tab':"Users",                        

                        'create_new_server_pool':"new_serverpool_link",
                        'edit_server_pool':"edit_serverpool_link",
                        'delete_server_pool':"delete_serverpool_link",
                        'select_all_server_pool':"selectAllServerPools",
                        'select_server_pool':".//*[@id='serverPoolsGrid']/tbody/tr[1]/td[1]/input",
                        'server_pool_next':"myModal-c3b764f0-3fdb-4822-9faa-8c29aec72c84']/div/div/div[2]/wizard/div/div[2]/div[2]/div[2]/button[2]",
                        'server_pool_name':".//*[@id='poolInfoForm']/div[1]/div/input",
                        'server_pool_desc':".//*[@id='poolInfoForm']/div[2]/div/textarea",
                        'select_all_servers':".//*[@id='serverTable']/thead/tr/th[1]/input",
                        'select_server_user_for_server_pool':".//*[@id='%(tid)s']/tbody/tr[%(rid)s]/td[1]/input",
                        'select_all_users':".//*[@id='users_table']/thead/tr/th[1]/input",
                        'select_user':".//*[@id='users_table']/tbody/tr/td[1]/input",
                        'server_pool_back':".//*[@id='myModal-c3b764f0-3fdb-4822-9faa-8c29aec72c84']/div/div/div[2]/wizard/div/div[2]/div[2]/div[2]/button[1]",
                        'server_pool_finish':".//*[@id='myModal-c3b764f0-3fdb-4822-9faa-8c29aec72c84']/div/div/div[2]/wizard/div/div[2]/div[2]/div[2]/button[3]",
                        'server_pool_cancel':".//*[@id='myModal-c3b764f0-3fdb-4822-9faa-8c29aec72c84']/div/div/div[2]/wizard/div/div[2]/div[2]/div[2]/button[4]",
                        
                        'discover_wiz_next':".//*[@id='page_discoveryWizard']/wizard/div/div[2]/div[2]/div[2]/button[2]",
                        'add_resource_type':".//*[@id='page_discovery_identifyresources']/button",
                        'select_resource_type':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[1]/select",
                        'IP_start_range':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[2]/ul/li[1]/input",
                        'IP_end_range':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[2]/ul/li[2]/input",
                        'resource_state':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[3]/select",
                        'select_server_pool':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[4]/div[1]/select",
                        'create_server_pool':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[4]/div[2]/button",
                        'select_chassis_cred':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[5]//*[@name='chassisCredentialId']",
                        'select_blade_cred':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[5]//*[@name='bladeCredentialId']",
                        'select_server_cred':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[5]//*[@name='serverCredentialId']",
                        'select_IOM_cred':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[5]//*[@name='iomCredentialId']",
                        'create_chassis_cred':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[5]/ul/li/ul/li[1]/div/div[2]/button",
                        'create_blade_cred':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[5]/ul/li/ul/li[2]/div/div[2]/button",
                        'create_iom_cred':".//*[@id='identifyResourcesGrid']/tbody/tr[%(rid)d]/td[5]/ul/li/ul/li[3]/div/div[2]/button",
                        'edit_cred':".//*[@id='identifyResourcesGrid']/tbody/tr[2]/td[5]/ul/li/div/div[2]/button[2]",
                        'delete_resource':".//*[@id='identifyResourcesGrid']/tbody/tr/td[6]/button",                        
                        'select_all_chassis':".//*[@id='collapseOne']/div/chassis-table/table/thead/tr/th[1]/input",
                        'select_chassis':".//*[@id='collapseOne']/div/chassis-table/table/tbody/tr/td[1]/input",
                        'manage_chassis_cred':"view_credentials",
                        'manage_blade_cred':"view_bladeCredential",
                        'manage_IOM_cred':"view_iomcredentials",
                        'manage_server_cred':".//*[@id='collapseThree']/div/form/div/div[2]/select",
                        'create_new_cred':"view_lnkAddCredential",
                        'get_rack_service_tags':".//rack-table//tbody/tr/td[3]",
                        'get_chassis_service_tags':".//chassis-table//tbody/tr/td[3]",
                        'manage_rack_credentials':".//rack-table/following-sibling::div//a[contains(.,'Manage Credentials')]",
                        'manage_chassis_credentials':".//chassis-table/following-sibling::div//a[contains(.,'Manage Credentials')]",
                        'ip_addressing':".//a[contains(text(), 'IP Addressing')]",
                        
                        'select_all_rack_servers':".//*[@id='collapseTwo']/div/rack-table/table/thead/tr/th[1]/input",
                        'select_server':".//*[@id='collapseTwo']/div/rack-table/table/tbody/tr/td[1]/input",
                        'finish_button':".//*[@id='page_discoveryWizard']/wizard/div/div[2]/div[2]/div[2]/button[3]",
                        'back_button':".//*[@id='page_discoveryWizard']/wizard/div/div[2]/div[2]/div[2]/button[1]",
                        'cancel_button':".//*[@id='page_discoveryWizard']/wizard/div/div[2]/div[2]/div[2]/button[4]",
                        'idrac_user':"user",
                        'idrac_pwd':"password",
                        'idrac_login':"submit_lbl",
                        'idrac_tree':"treelist",
                        'idrac_set_power_state':"//table[@id='infolist_table4']/tbody/tr/td/div/ul/li[@id='pwrtargetTR']/a/span",
                        'idrac_da_frame':"da",
                        'idrac_sys_frame':"sysIframe",
                        'idrac_get_power_state':"pwState",
                        'idrac_hardware_tab':"//div[@id='treelist']//table[@id='tbl_C18']//td[3]/a[1]/img[1]",
                        'idrac_memory':"a_Memory",
                        'idrac_memory_row_count':".//*[@id='memory_table']/tbody/tr",
                        'idrac_memory_table_header':".//*[@id='memory_table']/thead/tr[1]/td",
                        'idrac_memory_table_header_col':".//*[@id='memory_table']/thead/tr[1]/td[%(hid)d]",
                        'idrac_memory_table_element':".//*[@id='memory_table']/tbody/tr[%(rid)d]/td[%(cid)d]",
                        
                        'credential_name':"credential_name",
                        'credential_username':"credential_username_edit",
                        'credential_password':"credential_password",
                        'credential_confirm_password':"credential_confirm_password",
                        'credential_domain':"credential_domain_edit",
                        'credential_snmp':"credential_snmpconfig",
                        'save_credential':"submit_credential_form",
                        'get_performance_data':".//*[@id='memoryMaximum']",
                        'jobs_inprogress_count':".//*[@class='globalAlerts']/div/button",
                        'verify_view_jobs_window':".//*[@class='globalAlerts']/span",
                        'get_discovery_jobs':".//*[contains(@class, 'alertResults')]/div[1]/div/ul",
                        'get_update_jobs':".//*[contains(@class, 'alertResults')]/div[2]/ul",
                        'close_compliance_rpt':"firmwareReportOkButton",
                        'schedule_update':"//*[@value='schedule']",
                        'set_schedule_date':".//*[@id='dpScheduleDate']/input",
                        'apply_firmware_update':"submit_form_updatefirmware"
                        
                }
        return ResourceObjects.get(key)
        
