"""
Author: Saikumar Kalyankrishnan
Created: Feb 22nd 2017
Description: Object Repository for Virtual Appliance Management Page
"""

class VirtualApplianceManagement():
    def VirtualApplianceManagementObjects (self, key):
        VirtualApplianceManagementObjects = {'title': "//*[@id='page_applianceManagement']//h1",
                                             'settingsList': "page_settingslist",
                                             'updateAppliance': "updateApplianceLink",
                                             'generateTSB': "generateTroubleshootLink",
                                             'editTZNTP': "lnkEditNTP",
                                             'formTZNTP': "edit_ntp_form",
                                             'updateTimezone': "select_ntp_timezone",
                                             'updatePreferredNTP': "preferred_ntp_server",
                                             'updateSecondaryNTP': "secondary_ntp_server",
                                             'currentTZ': "timeZone",
                                             'currentPNTP': "ntpServer",
                                             'currentSNTP': "secondaryNtpServer",
                                             'editRepoPath': "editRepositoryPathLink",
                                             'formRepoPath': "repositoryForm",
                                             'availableVersion': "availableVersion",
                                             'currentVersion': "currentVersion",
                                             'updateRepoPath': "updateRepositoryPath",
                                             'currentRepoPath': "repositoryPath",
                                             'releaseNotes': "//*[@id='page_applianceManagement']//a[normalize-space(contains(text(), 'asmdocs'))]",
                                             'editProxy': "editProxySettingsLink",
                                             'formProxy': "proxySettingsForm",
                                             'currentProxy': "enableProxy",
                                             'useProxy': "useProxySettings",
                                             'serverProxy': "ipAddress",
                                             'portProxy': "portNumber",
                                             'proxyCreds': "useProxyCreds",
                                             'proxyUsername': "username",
                                             'proxyPassword': "password",
                                             'proxyConfirmPW': "verifyPassword",
                                             'proxySave': "submitProxySettings",
                                             'proxyTest': "btnTestProxy",
                                             'proxyCancel': "cancel_ntp_form",
                                             'editDHCP': "editDhcpSettings",
                                             'formDHCP': "dhcpSettingsForm",
                                             'currentDHCPStatus':"enableDhcpServer",
                                             'checkEnableDHCP': "enableDHCPServer",
                                             'DHCPSubnet': "subnet",
                                             'DHCPNetmask': "netmask",
                                             'DCHPStartIP': "startingIpAddress",
                                             'DHCPEndIP': "endingIpAddress",
                                             'DHCPLeaseDays': "defaultLeaseTimeDays",
                                             'DHCPLeaseHours': "defaultLeaseTimeHours",
                                             'DHCPLeaseMinutes': "defaultLeaseTimeMinutes",
                                             'DHCPLeaseSeconds': "defaultLeaseTimeSeconds",
                                             'DHCPMaxDays': "maxLeaseTimeDays",
                                             'DHCPMaxHours': "maxLeaseTimeHours",
                                             'DHCPMaxMinutes': "maxLeaseTimeMinutes",
                                             'DHCPMaxSeconds': "maxLeaseTimeSeconds",
                                             'DCHPGateway': "gateway",
                                             'DCHPDNS': "dns",
                                             'DCHPDomain': "domain",
                                             'DHCPSubmit': "submitDhcpSettings",
                                             'DHCPCancel': "btnCancel",
                                             'generateCert': "generateSigningCertLink",
                                             'certValidFrom': "validFrom",
                                             'certValidTo': "validTo",
                                             'formGenCert': "signingRequestForm",
                                             'certDistName': "distinguishedName",
                                             'certBusinessName': "businessName",
                                             'certDeptName': "deptName",
                                             'certLocality': "locality",
                                             'certState': "state",
                                             'certCountry': "country",
                                             'certEmail': "email",
                                             'certGenerate': "generateCertSubmit",
                                             'certCancel': "cancelBtn",
                                             'uploadCert': "uploadCertLink",
                                             'formUploadCert': "page_uploadCertificate",
                                             'uploadCertFile': "idLocationFileUpload",
                                             'uploadCertSubmit': "btnSubmit",
                                             'uploadCertCancel': "btnCancel",
                                             'addLicense': "editLicenseManagementLink",
                                             'mainLicenseType':"type",
                                             'mainTotalResources': "totalnodes",
                                             'mainResourcesUsed': "usednodes",
                                             'mainResourcesAvailable': "availablenodes",
                                             'formLicense': "page_licenseManagementForm",
                                             'uploadLicense': "idLocationFileUpload",
                                             'licenseType': "//*[@id='page_licenseManagementForm']/fieldset/div[2]/p",
                                             'totalResources': "//*[@id='page_licenseManagementForm']/fieldset/div[3]/p",
                                             'licenseExpiry': "//*[@id='page_licenseManagementForm']/fieldset/div[4]/p",
                                             'saveLicense': "btnAddLicenseForm",
                                             'cancelLicense': "btnCancelLicenseForm",
                                             'editServiceTag': "editServiceTagLink",
                                             'formServiceTag': "editServiceTagForm",
                                             'updateServiceTag': "//input[@id='serviceTag']",
                                             'saveServiceTag': "btnSaveServiceTag",
                                             'cancelServiceTag': "btnCancelServiceTag",
                                             'currentServiceTag': "serviceTag",
                                             'currentIPPorts': "ipVerificationPorts",
                                             'editIPPort': "editIpVerificationLink",
                                             'formIPPORT': "page_Appliance_Update",
                                             'updateIPPort': "//*[@id='page_Appliance_Update']//input[@name='ipVerificationPorts']",
                                             'saveIPPort': "btnSaveServiceTag",
                                             'cancelIPPort': "btnCancelServiceTag",
                                             'VAMSave': "submit_ntp_form",
                                             'VAMCancel': "cancel_ntp_form",
                                             'loginPageLogo': "//i[@alt='Application Logo']",
                                             'username': "loginUsername",
                                             'password': "loginPassword",
                                             'remember': "rememberMe",
                                             'login': "btnLogin",
                                             'loginError': "//div[@class='text-center ng-binding']",
        }
        return VirtualApplianceManagementObjects.get(key)